{%- if cookiecutter.web_book -%}
project:
  type: book

book:
{%- else -%}
project:
  type: website

website:
{%- endif %}
  page-navigation: true
  title: {{cookiecutter.project_name}} 
  author: {{cookiecutter.full_name}}
  description: {{cookiecutter.project_short_description}}
  site-url: "https://{{cookiecutter.github_username}}/{{cookiecutter.repo_name}}/" 
  repo-url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.repo_name}} 
  repo-actions: [issue]
  
  page-footer:
    right: "This page is based on Openscape's [Quarto Site Template](https://github.com/Openscapes/quarto-website-tutorial) and built with [Quarto](https://quarto.org/) ."
    left: "&copy; CC BY-SA 4.0, {% now 'utc', '%Y' %}"
    
  sidebar:
    logo: "images/data-duck.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://cookiecutter.readthedocs.io/en/stable/
        text: "Cookiecutter Project Templates"
      - icon: github
        href: https://github.com/{{cookiecutter.github_username}}
        text: "{{cookiecutter.full_name}}'s GitHub"
{% if cookiecutter.web_book %}
  chapters:
    - index.qmd
  appendices:
    - about.qmd
{%- else %}
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Us
        icon: dot
      - href: slides/presentation_demo.qmd
        text: Example Presentation
        icon: dot
{%- endif %}

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
{%- if cookiecutter.web_book -%}
  pdf:
    documentclass: scrreprt # LaTex document class as implemented by KOMA-script (book, report, article, letter)
    toc: true
    lof: true
    lot: true
{%- endif %}

filters:
  - quarto


